#cloud-config
packages:
  - git
  - python3-venv

runcmd:
  - git clone https://github.com/cowrie/cowrie.git /opt/cowrie
  - python3 -m venv /opt/cowrie/cowrie-env
  - source /opt/cowrie/cowrie-env/bin/activate
  - pip install --upgrade pip
  - pip install -r /opt/cowrie/requirements.txt
  - cp /opt/cowrie/etc/cowrie.cfg.dist /opt/cowrie/etc/cowrie.cfg
  - sed -i 's/listen_port = 2222/listen_port = 22/' /opt/cowrie/etc/cowrie.cfg
  - /opt/cowrie/bin/cowrie start
  # This exposes a fake SSH service, DO NOT USE THIS TEMPLATE IN PRODUCTION